export const tracks = [
  
  {
    "fanlink": "lnk.bayzamusic.com/TakeMeHome",
    "description": "Bayza brings \"Take Me Home\" under the German label \"The Night Drive\". The inspiration for this track was to try to transmit nighty vibes that are suited perfectly for car driving or club parties because of its modern house music style.",
    "title": "A",
    "type": "Releases",
    "year": 2021,
    "cover": "take-me-home",
    "label": "The Night Drive",
    "duration": "2:58",
    "video": "BwKO7sfFVAA",
    "artists": "Advait",
    "date": "2021-06-25 00:00:00",
    "release": "take-me-home",
    "genre": "Deep House"
  },
  {
    "fanlink": "lnk.bayzamusic.com/ThumbsRemix",
    "description": "Hi guys, I hope you like this track, someone asked me to remix Thumbs by Sabrina Carpenter, I liked the original song when I first listened to it so I decided to finish this remix. I've also uploaded an <a class=\"text-white\" href=\"https://www.youtube.com/watch?v=9u_UwD-WpSE\" target=\"_blank\" title=\"Bayza - Thumbs | Instrumental Version\">Instrumental Version</a></b> for those who want to listen without the vocals.",
    "title": "Budha",
    "type": "Bootlegs/Remixes",
    "year": 2021,
    "cover": "thumbs",
    "label": null,
    "duration": "3:23",
    "video": "SPlamGgkl00",
    "artists": "Advait",
    "date": "2021-12-02 00:00:00",
    "release": "thumbs-remix",
    "genre": "Dance",
    "link": "-bootlegs"
  },
  {
    "fanlink": "lnk.bayzamusic.com/Pirhan",
    "description": null,
    "title": "Rabindranath Tagore",
    "type": "Releases",
    "year": 2021,
    "cover": "pirhan",
    "label": "Ario Records",
    "duration": "4:55",
    "video": "_HNN88li9kI",
    "artists": "Advait",
    "date": "2021-12-15 00:00:00",
    "release": "pirhan",
    "genre": "Organic House / Deep House"
  },
  {
    "album": "Passages",
    "fanlink": "lnk.bayzamusic.com/DesertRose",
    "description": "This is the instrumental version of \"<a class=\"text-white\" href=\"https://bayzamusic.com/releases/2020-bootlegs/desert-rose-enta-omri\" target=\"_blank\" title=\"Noel Kharman - Desert Rose / \u0627\u0646\u062a \u0639\u0645\u0631\u064a Mashup (Bayza Remix)\">Noel Kharman - Desert Rose / \u0627\u0646\u062a \u0639\u0645\u0631\u064a Mashup (Bayza Remix)</a>\"",
    "title": "Kalpana Chavla",
    "type": "Releases",
    "artists": "Advait",
    "cover": "passages",
    "label": null,
    "duration": "3:49",
    "video": "h1aLkuT0ctI",
    "year": 2021,
    "date": "2021-12-30 00:00:01",
    "release": "desert-rose",
    "genre": "Deep House"
  },
  
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/ImFalling",
    "description": null,
    "title": "Cinderella",
    "type": "Releases",
    "artists": "Advait",
    "cover": "im-falling",
    "label": "DeepShine Records",
    "duration": "3:32",
    "video": "EZodqty3HLA",
    "year": 2022,
    "date": "2022-01-21 00:00:00",
    "release": "im-falling",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/CallOut",
    "description": null,
    "title": "Budha",
    "type": "Releases",
    "artists": "Advait",
    "cover": "call-out",
    "label": null,
    "duration": "3:40",
    "video": "vlU7crlYW4I",
    "year": 2022,
    "date": "2022-02-25 00:00:01",
    "release": "call-out",
    "genre": "Electropop"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/Pieces",
    "description": null,
    "title": "Lakshmibai Bhaurao Patil",
    "type": "Releases",
    "artists": "Advait",
    "cover": "pieces",
    "label": null,
    "duration": "3:03",
    "video": "VTscrLkd20s",
    "year": 2022,
    "date": "2022-05-06 00:00:00",
    "release": "pieces",
    "genre": "Dance"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/ShowMe",
    "description": null,
    "title": "Mahatma Jotiba Phule",
    "type": "Releases",
    "artists": "Advait",
    "cover": "show-me-what-you-feel",
    "label": "Melodicity Records",
    "duration": "2:44",
    "video": "trdqaqZCVEU",
    "year": 2022,
    "date": "2022-06-10 00:00:00",
    "release": "show-me",
    "genre": "Dance"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/YoungFree",
    "description": null,
    "title": "Shiv Shankar",
    "type": "Releases",
    "artists": "Advait",
    "cover": "young-free",
    "label": "Miami Beats",
    "duration": "3:23",
    "video": "-vVutcvq5I4",
    "year": 2022,
    "date": "2022-07-08 00:00:00",
    "release": "young-free",
    "genre": "Tropical House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/WhyCantItBe",
    "description": null,
    "title": "Castle",
    "type": "Releases",
    "artists": "Advait",
    "cover": "why-cant-it-be",
    "label": "Storm Music Group",
    "duration": "2:58",
    "video": "BRRXzu2Q1-g",
    "year": 2022,
    "date": "2022-08-05 00:00:00",
    "release": "why-cant-it-be",
    "genre": "Dance"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/OnYourMind",
    "description": null,
    "title": "Abstract Painting",
    "type": "Releases",
    "artists": "Advait",
    "cover": "on-your-mind",
    "label": "Different Twins/Twin Girls Records",
    "duration": "2:34",
    "video": "0fdvG4GRRFA",
    "year": 2022,
    "date": "2022-09-01 00:00:00",
    "release": "on-your-mind",
    "genre": "Dance"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/TrueLovers",
    "description": null,
    "title": "Guru Nanak",
    "type": "Releases",
    "artists": "Advait",
    "cover": "true-lovers",
    "label": "Mark Music Records",
    "duration": "3:01",
    "video": "_UNJ54LGdKc",
    "year": 2022,
    "date": "2022-11-04 00:00:00",
    "release": "true-lovers",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/LunchboxFriends",
    "description": null,
    "title": "Bappa & Shiv Shankar",
    "type": "Releases",
    "artists": "Advait",
    "cover": "lunchbox-friends",
    "label": "Gangster City",
    "duration": "2:53",
    "video": "HRrD3Mj3sEY",
    "year": 2022,
    "date": "2022-12-09 00:00:00",
    "release": "lunchbox-friends",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/Madhouse",
    "description": null,
    "title": "Shri Krishna",
    "type": "Releases",
    "artists": "Advait",
    "cover": "madhouse",
    "label": "The Night Drive",
    "duration": "2:34",
    "video": "Hj_kBReLOQA",
    "year": 2023,
    "date": "2023-03-10 00:00:00",
    "release": "madhouse",
    "genre": "Deep House"
  },
  {
    "album": null,
    "fanlink": "lnk.bayzamusic.com/LightComesUp",
    "description": null,
    "title": "Chatrapati Shivaji Maharaj",
    "type": "Releases",
    "artists": "Advait",
    "cover": "light-comes-up",
    "label": "Twins Girls Records",
    "duration": "2:49",
    "video": "uesHdgS0o04",
    "year": 2023,
    "date": "2023-05-11 00:00:00",
    "release": "light-comes-up",
    "genre": "Chill House"
  },
 
 
  
  {
    "album": "Breeze",
    "fanlink": "lnk.bayzamusic.com/Breeze",
    "description": null,
    "title": "Vithal",
    "type": "Releases",
    "artists": "Advait",
    "cover": "breeze",
    "label": "",
    "duration": "2:53",
    "video": "vIVwrWVBA2E",
    "year": 2023,
    "date": "2023-07-28 00:00:05",
    "release": "breeze",
    "genre": "Deep House"
  },
  {
    // -----------------------
    "album": "",
    "fanlink": "lnk.bayzamusic.com/NowOrNever",
    "description": null,
    "title": "Abstract",
    "type": "Releases",
    "artists": "Advait",
    "cover": "now-or-never",
    "label": "DeepShine Records",
    "duration": "2:36",
    "video": "CS-AQefwkRk",
    "year": 2023,
    "date": "2023-08-11 00:00:00",
    "release": "now-or-never",
    "genre": "Deep House"
  },
  {
    "album": "",
    "fanlink": "lnk.bayzamusic.com/Obsession",
    "description": null,
    "title": "shri Swami Samarth",
    "type": "Drawing",
    "artists": "Advait",
    "cover": "obsession",
    // "label": "DeepShine Records",
    // "duration": "2:45",
    // "video": "KNmD8d2bnp0",
    "year": 2023,
    "date": "2023-12-18 00:00:00",
    "release": "obsession",
    // "genre": "Deep House"
  }
];